version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "npm"
    directory: "/apps/tgvcbot"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/apps/website"
    schedule:
      interval: "daily"